oplata_uslug = float(input('Input total amount: '))
kurs = float(input('Input current DOLLAR rate: '))
salary = float(input('Input your salary: '))
ostatok_kompanii = round(oplata_uslug - salary, 2)
procent_zp = round(((salary*95)/100), 2)
ostatok_kompanii_bez5procentov = round(((ostatok_kompanii*95)/100), 2)
five_percent = round(((oplata_uslug*5)/100), 2)
buhgalteria_and_kovorking = round(float(ostatok_kompanii_bez5procentov*kurs) - float(1040))
print(f'Поменять нужно для оплаты налогов, бух услуг, и коворкинга: {ostatok_kompanii_bez5procentov} $')
print(f'5 процентов, которые нужно оставить на счету: {five_percent} $')
print(f'Для коворкинга и бух услуг нужно снять: {buhgalteria_and_kovorking} грн')
print(f'По этим расчетам коворкинг должен составлять примерно {float(buhgalteria_and_kovorking - 700)} грн. Это Правильно?')